### ISSUE TITLE
template error (issues_didyoumean_event_type) with 2.4.4

### ISSUE THREAD

**Issue by akohlsmith** [abahgat/redmine_didyoumean#54]
The plugin worked fine on 2.3. With 2.4.4, opening a specific issue results in the following crash:

```
Completed 500 Internal Server Error in 677.4ms

ActionView::Template::Error (undefined local variable or method `issues_didyoumean_event_type' for #<#<Class:0xbfea1b8>:0xd202b98>):
    19:   };
    20: </script>
    21:
    22: <%= javascript_tag "observeIssueSubjectField('#{@project.id}', #{@issue.id or '\'\''}, '#{issues_didyoumean_event_type}');" %>
  lib/redmine/hook.rb:111:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/issues/_form.html.erb:44:in `block in _app_views_issues__form_html_erb___582396499_113230890'
  app/helpers/application_helper.rb:984:in `labelled_fields_for'
  app/views/issues/_form.html.erb:1:in `_app_views_issues__form_html_erb___582396499_113230890'
  app/views/issues/_edit.html.erb:8:in `block in _app_views_issues__edit_html_erb__915690113_112227570'
  app/helpers/application_helper.rb:977:in `labelled_form_for'
  app/views/issues/_edit.html.erb:1:in `_app_views_issues__edit_html_erb__915690113_112227570'
  app/controllers/issues_controller.rb:124:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:121:in `show'
```
