### ISSUE TITLE
Does not work with 4.1.1

### ISSUE THREAD

**Issue by col-panic** [abahgat/redmine_didyoumean#94]
First you have to change the mysql2 dependency to 0.5.0, but the subsequent migrate fails

```
bundle exec rake db:migrate RAILS_ENV=production 
rake aborted!
NoMethodError: undefined method `alias_method_chain' for ThinkingSphinx::Deletion::RealtimeDeletion:Class
Did you mean?  alias_method
/srv/services/redmine.medelexis.ch/plugins/redmine_didyoumean/lib/redmine_didyoumean/patches/monkey_after_destroy_patch.rb:13:in `block in patch_after_destroy'
/srv/services/redmine.medelexis.ch/plugins/redmine_didyoumean/lib/redmine_didyoumean/patches/monkey_after_destroy_patch.rb:8:in `class_eval'
/srv/services/redmine.medelexis.ch/plugins/redmine_didyoumean/lib/redmine_didyoumean/patches/monkey_after_destroy_patch.rb:8:in `patch_after_destroy'
/srv/services/redmine.medelexis.ch/plugins/redmine_didyoumean/lib/redmine_didyoumean/patches/monkey_after_destroy_patch.rb:21:in `block in <top (required)>'
/srv/services/redmine.medelexis.ch/plugins/redmine_didyoumean/lib/redmine_didyoumean/patches/monkey_after_destroy_patch.rb:19:in `each'
/srv/services/redmine.medelexis.ch/plugins/redmine_didyoumean/lib/redmine_didyoumean/patches/monkey_after_destroy_patch.rb:19:in `<top (required)>'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/srv/services/redmine.medelexis.ch/plugins/redmine_didyoumean/init.rb:30:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:51:in `each'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
/srv/services/redmine.medelexis.ch/config/environment.rb:16:in `<top (required)>'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/application.rb:337:in `require_environment!'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/var/lib/gems/2.5.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```

**Comment by Luckyvb** [comment]
[devcoffee for create patch](https://github.com/devcoffee/redmine_didyoumean/commit/d17413e1152b4e530174e291d1a545ad463c5b55)

**Comment by abahgat** [comment]
Thanks for the pointers, unfortunately I no longer actively work with Redmine so maintaining this is becoming a bit more difficult for me.
I will take a look at the patch above and look into merging it though if it's confirmed it fixes the problem.

**Comment by col-panic** [comment]
Solved via https://github.com/devcoffee/redmine_didyoumean.git
